export type StudentRequestStatus =
  "Pending" | "Ready" | "Completed" | "Cancelled";

export type StudentRequest = {
  id: string;
  document: "COR" | "COE";
  submittedOn: string;
  status: StudentRequestStatus;
};

export type ScheduleDay =
  "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday";

export const academicViews = [
  "Schedule",
  "Subjects",
  "Grades",
  "Attendance",
  "Curriculum",
] as const;

export type AcademicView = (typeof academicViews)[number];

export const studentDemoData = {
  identity: {
    firstName: "John Paul",
    lastName: "Reyes",
    fullName: "John Paul Reyes",
    studentId: "DEMO-STU-2026-0142",
    email: "john.reyes@example.invalid",
    program: "BSIS — Bachelor of Science in Information Systems",
    programCode: "BSIS",
    campus: "IIT Campus",
    yearLevel: "3rd Year",
    academicStatus: "Active Student",
  },
  term: {
    academicYear: "2026–2027",
    semester: "2nd Semester",
    section: "BSIS-3A",
  },
  today: {
    day: "Friday" as ScheduleDay,
    date: "2027-02-26",
    nextClassId: "is203-fri",
  },
  subjects: [
    {
      id: "is201",
      code: "IS 302",
      title: "Systems Design",
      units: 3,
      instructor: "M. Santos",
      status: "Enrolled",
    },
    {
      id: "is203",
      code: "IS 304",
      title: "Project Management",
      units: 3,
      instructor: "L. Dela Cruz",
      status: "Enrolled",
    },
    {
      id: "ge201",
      code: "GE 302",
      title: "Applied Research",
      units: 3,
      instructor: "A. Garcia",
      status: "Enrolled",
    },
    {
      id: "is205",
      code: "IS 306",
      title: "Enterprise Applications",
      units: 3,
      instructor: "R. Lim",
      status: "Enrolled",
    },
    {
      id: "pe202",
      code: "PE 202",
      title: "Movement and Wellness",
      units: 2,
      instructor: "J. Cruz",
      status: "Enrolled",
    },
  ],
  schedule: [
    {
      id: "is201-mon",
      subjectId: "is201",
      day: "Monday",
      start: "08:00",
      end: "09:30",
      room: "Room 204",
    },
    {
      id: "is203-mon",
      subjectId: "is203",
      day: "Monday",
      start: "10:30",
      end: "12:00",
      room: "Room 302",
    },
    {
      id: "is205-wed",
      subjectId: "is205",
      day: "Wednesday",
      start: "08:00",
      end: "09:30",
      room: "Computer Lab 2",
    },
    {
      id: "ge201-wed",
      subjectId: "ge201",
      day: "Wednesday",
      start: "13:00",
      end: "14:30",
      room: "Room 108",
    },
    {
      id: "is205-thu",
      subjectId: "is205",
      day: "Thursday",
      start: "10:30",
      end: "12:00",
      room: "Computer Lab 2",
    },
    {
      id: "pe202-thu",
      subjectId: "pe202",
      day: "Thursday",
      start: "13:00",
      end: "14:00",
      room: "Covered Court",
    },
    {
      id: "is201-fri",
      subjectId: "is201",
      day: "Friday",
      start: "08:00",
      end: "09:30",
      room: "Room 204",
    },
    {
      id: "is203-fri",
      subjectId: "is203",
      day: "Friday",
      start: "10:30",
      end: "12:00",
      room: "Room 302",
    },
    {
      id: "ge201-fri",
      subjectId: "ge201",
      day: "Friday",
      start: "13:00",
      end: "14:30",
      room: "Room 108",
    },
  ],
  grades: [
    {
      code: "IS 302",
      title: "Systems Design",
      units: 3,
      academicYear: "2026–2027",
      semester: "2nd Semester",
      grade: null,
      status: "Not yet released",
    },
    {
      code: "IS 304",
      title: "Project Management",
      units: 3,
      academicYear: "2026–2027",
      semester: "2nd Semester",
      grade: null,
      status: "Not yet released",
    },
    {
      code: "GE 302",
      title: "Applied Research",
      units: 3,
      academicYear: "2026–2027",
      semester: "2nd Semester",
      grade: null,
      status: "Not yet released",
    },
    {
      code: "IS 306",
      title: "Enterprise Applications",
      units: 3,
      academicYear: "2026–2027",
      semester: "2nd Semester",
      grade: null,
      status: "Not yet released",
    },
    {
      code: "PE 302",
      title: "Movement and Wellness",
      units: 2,
      academicYear: "2026–2027",
      semester: "2nd Semester",
      grade: null,
      status: "Not yet released",
    },
    {
      code: "IS 301",
      title: "Enterprise Systems",
      units: 3,
      academicYear: "2026–2027",
      semester: "1st Semester",
      grade: "1.75",
      status: "Released",
    },
    {
      code: "IS 303",
      title: "Information Assurance",
      units: 3,
      academicYear: "2026–2027",
      semester: "1st Semester",
      grade: "1.50",
      status: "Released",
    },
    {
      code: "IS 305",
      title: "Technology Planning",
      units: 3,
      academicYear: "2026–2027",
      semester: "1st Semester",
      grade: "2.00",
      status: "Released",
    },
    {
      code: "GE 301",
      title: "Contemporary Philippine Society",
      units: 3,
      academicYear: "2026–2027",
      semester: "1st Semester",
      grade: "1.75",
      status: "Released",
    },
    {
      code: "IS 103",
      title: "Information Systems Concepts",
      units: 3,
      academicYear: "2025–2026",
      semester: "2nd Semester",
      grade: "1.75",
      status: "Released",
    },
    {
      code: "GE 102",
      title: "Readings in Philippine History",
      units: 3,
      academicYear: "2025–2026",
      semester: "2nd Semester",
      grade: "1.50",
      status: "Released",
    },
    {
      code: "CS 104",
      title: "Introduction to Programming",
      units: 3,
      academicYear: "2025–2026",
      semester: "2nd Semester",
      grade: "2.00",
      status: "Released",
    },
    {
      code: "IS 201",
      title: "Data Management",
      units: 3,
      academicYear: "2025–2026",
      semester: "1st Semester",
      grade: "1.75",
      status: "Released",
    },
    {
      code: "IS 203",
      title: "Systems Analysis",
      units: 3,
      academicYear: "2025–2026",
      semester: "1st Semester",
      grade: "2.00",
      status: "Released",
    },
    {
      code: "GE 201",
      title: "Ethics and Society",
      units: 3,
      academicYear: "2025–2026",
      semester: "1st Semester",
      grade: "1.50",
      status: "Released",
    },
    {
      code: "IS 205",
      title: "Web Systems",
      units: 3,
      academicYear: "2025–2026",
      semester: "1st Semester",
      grade: "1.75",
      status: "Released",
    },
    {
      code: "IS 103",
      title: "Information Systems Concepts",
      units: 3,
      academicYear: "2024–2025",
      semester: "2nd Semester",
      grade: "1.75",
      status: "Released",
    },
    {
      code: "GE 102",
      title: "Readings in Philippine History",
      units: 3,
      academicYear: "2024–2025",
      semester: "2nd Semester",
      grade: "1.50",
      status: "Released",
    },
    {
      code: "CS 104",
      title: "Introduction to Programming",
      units: 3,
      academicYear: "2024–2025",
      semester: "2nd Semester",
      grade: "2.00",
      status: "Released",
    },
    {
      code: "IS 101",
      title: "Computing Fundamentals",
      units: 3,
      academicYear: "2024–2025",
      semester: "1st Semester",
      grade: "1.75",
      status: "Released",
    },
    {
      code: "GE 101",
      title: "Communication Skills",
      units: 3,
      academicYear: "2024–2025",
      semester: "1st Semester",
      grade: "1.50",
      status: "Released",
    },
    {
      code: "MATH 101",
      title: "College Algebra",
      units: 3,
      academicYear: "2024–2025",
      semester: "1st Semester",
      grade: "2.00",
      status: "Released",
    },
  ],
  attendance: [
    {
      subjectId: "is201",
      present: 8,
      late: 1,
      absent: 0,
      recent: [
        { date: "19 Feb 2027", status: "Present" },
        { date: "12 Feb 2027", status: "Late" },
        { date: "05 Feb 2027", status: "Present" },
      ],
    },
    {
      subjectId: "is203",
      present: 7,
      late: 0,
      absent: 1,
      recent: [
        { date: "19 Feb 2027", status: "Present" },
        { date: "12 Feb 2027", status: "Absent" },
        { date: "05 Feb 2027", status: "Present" },
      ],
    },
    {
      subjectId: "ge201",
      present: 5,
      late: 0,
      absent: 0,
      recent: [
        { date: "26 Feb 2027", status: "Present" },
        { date: "19 Feb 2027", status: "Present" },
      ],
    },
    {
      subjectId: "is205",
      present: 4,
      late: 0,
      absent: 0,
      recent: [
        { date: "25 Feb 2027", status: "Present" },
        { date: "18 Feb 2027", status: "Present" },
      ],
    },
  ],
  curriculum: [
    {
      year: "1st Year",
      semester: "1st Semester",
      status: "Completed",
      subjects: [
        "Computing Fundamentals",
        "College Algebra",
        "Communication Skills",
      ],
    },
    {
      year: "1st Year",
      semester: "2nd Semester",
      status: "Completed",
      subjects: [
        "Introduction to Programming",
        "Information Systems Concepts",
        "Readings in Philippine History",
      ],
    },
    {
      year: "2nd Year",
      semester: "1st Semester",
      status: "Completed",
      subjects: [
        "Data Management",
        "Systems Analysis",
        "Ethics and Society",
        "Web Systems",
      ],
    },
    {
      year: "2nd Year",
      semester: "2nd Semester",
      status: "Completed",
      subjects: ["Networking Fundamentals", "Systems Design", "Statistics"],
    },
    {
      year: "3rd Year",
      semester: "1st Semester",
      status: "Completed",
      subjects: [
        "Enterprise Systems",
        "Information Assurance",
        "Technology Planning",
        "Contemporary Philippine Society",
      ],
    },
    {
      year: "3rd Year",
      semester: "2nd Semester",
      status: "Current",
      subjects: [
        "Systems Design",
        "Project Management",
        "Applied Research",
        "Enterprise Applications",
        "Movement and Wellness",
      ],
    },
  ],
  documents: {
    COR: {
      available: true,
      title: "Certificate of Registration",
      term: "2026–2027 · 2nd Semester",
    },
    COE: {
      available: true,
      title: "Certificate of Enrollment",
      term: "2026–2027 · 2nd Semester",
    },
  },
  requests: [
    {
      id: "DEMO-REQ-104",
      document: "COE",
      submittedOn: "23 Feb 2027",
      status: "Pending",
    },
    {
      id: "DEMO-REQ-101",
      document: "COR",
      submittedOn: "16 Feb 2027",
      status: "Ready",
    },
    {
      id: "DEMO-REQ-096",
      document: "COE",
      submittedOn: "08 Feb 2027",
      status: "Completed",
    },
    {
      id: "DEMO-REQ-091",
      document: "COR",
      submittedOn: "02 Feb 2027",
      status: "Cancelled",
    },
  ] satisfies StudentRequest[],
  announcements: [
    {
      id: "notice-1",
      date: "25 Feb 2027",
      category: "Campus",
      title: "Sample study space update",
      summary:
        "A fictional campus notice for the Student portal demonstration.",
    },
    {
      id: "notice-2",
      date: "23 Feb 2027",
      category: "Program",
      title: "Sample BSIS advising note",
      summary:
        "A fictional program notice. Confirm academic guidance with the appropriate school office.",
    },
    {
      id: "notice-3",
      date: "20 Feb 2027",
      category: "Institution",
      title: "Sample student services update",
      summary:
        "An illustrative institution-wide notice. No real service change is represented.",
    },
  ],
  calendarEvents: [
    {
      id: "event-is201",
      date: "2027-02-26",
      time: "08:00",
      title: "Systems Design",
      detail: "Room 204",
      category: "Class",
    },
    {
      id: "event-is203",
      date: "2027-02-26",
      time: "10:30",
      title: "Project Management",
      detail: "Room 302",
      category: "Class",
    },
    {
      id: "event-ge201",
      date: "2027-02-26",
      time: "13:00",
      title: "Applied Research",
      detail: "Room 108",
      category: "Class",
    },
    {
      id: "event-sample",
      date: "2027-03-02",
      time: "11:00",
      title: "Sample academic planning date",
      detail: "Illustrative calendar item",
      category: "Sample event",
    },
  ],
} as const;

export function formatScheduleTime(value: string) {
  const localTime = new Date(`2000-01-01T${value}:00+08:00`);
  return new Intl.DateTimeFormat("en-PH", {
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
    timeZone: "Asia/Manila",
  }).format(localTime);
}

export function formatScheduleRange(start: string, end: string) {
  return `${formatScheduleTime(start)} – ${formatScheduleTime(end)}`;
}
